apiVersion: apps/v1
kind: Deployment
metadata:
  name: huytm-demo2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: huytm-demo2
  template:
    metadata:
      labels:
        app: huytm-demo2
    spec:
      imagePullSecrets:
      - name: dockerhub-creds
      containers:
      - name: huytm-demo2
        image: huytm1996/huytm-demo2:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: huytm-demo2-service
spec:
  selector:
    app: huytm-demo2
  ports:
    - name: http
      port: 80
      targetPort: 80
      nodePort: 31334
  type: NodePort